### ISSUE TITLE
Create-React-App Support

### ISSUE THREAD

**Issue by jacobp100** [jacobp100/cssta#16]
CRA 2 will support babel-plugin-macros. This means we can optimise. The first step is to support babel-plugin-macros (#15).

We probably won't run this in development.

However, the CSS output will also need to be managed. There are several options, some of which may not be feasible.

* Create a CSS file in `<app>/public`
* Create a CSS file and import it so it's handled by the build tool
    * You'd probably not include this in git
* Create multiple CSS files and import them
    * Definitely wouldn't include in git
    * Could help with the case where files are deleted, but the CSS could be retained
    * Could ensure a half-prepared CSS file wouldn't get processed too early

###### TODO

* [x] Add babel-plugin macros support
* [x] CSS extraction in macro
* [ ] Test when CRA2 comes out

**Comment by jacobp100** [comment]
Went with multiple files to enable code splitting. It only produces these files on build. We’ll likely want a cleanup tool, or recommend people .gitignore these files

**Comment by jacobp100** [comment]
Reopening because this needs to be tested on CRA2.

**Comment by jacobp100** [comment]
We removed support for web for the moment. We support babel-plugin-macros, we'd just need to restore CSS generation for this to happen

**Comment by jacobp100** [comment]
Closing for now
